shutdown_timeout: 120s
http_server:
  port: 2530
  cors:
    allow_origins:
logger:
  file_path: "/logs/chat/logs.json"
  use_local_time: false
  file_max_size_in_mb: 10
  file_max_age_in_days: 30
  max_backup: 0
  compress: false
websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
chat:
  write_wait: 10s
  pong_wait: 60s
  max_message_size: 512
