# .air.toml for chatapp
root = "."
tmp_dir = "tmp"

[build]
cmd = "go mod tidy && go build -o ./tmp/manager ./cmd/manager/main.go"
bin = "./tmp/manager start"
include_ext = ["go", "yaml", "yml", "json", "mod", "sum"]
exclude_dir = ["cli", "tmp", "logs", "deploy", "example"]
include_dir = ["cmd/manager", "app/manager", "adapter", "config", "pkg", "types", "outbox", "protobuf", "event"]
delay = 1000 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"