name: Chat Build AND Deploy On Docker

on:
  push:
    tags:
      - 'chat/v*'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Check Triggering Tag
        if: startsWith(github.ref, 'refs/tags/chat/v')
        run: echo "Tag ${GITHUB_REF#refs/tags/}"

      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Run Tests
        run: make chat-test
