name: Go Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]
    paths:
      - 'adapter/**'
      - 'app/**'
      - 'cli/**'
      - 'cmd/**'
      - 'config/**'
      - 'event/**'
      - 'outbox/**'
      - 'pkg/**'
      - 'protobuf/**'
      - 'types/**'

  push:
    tags:
      - '*/v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: lint
        run: make lint
